### ISSUE TITLE
DESIGN: Logo

### ISSUE THREAD

**Issue by prithvijitguha** [prithvijitguha/MyView#141]
Logo needs better design. 

Create new logo and upload to docs and static folder 

logo located at ./static/assets/MyViewLogo.jpg

favicon located at ./static/assets/MyViewFavicon.png

**Comment by guilherme-svg** [comment]
how do i help with the logo?

**Comment by prithvijitguha** [comment]
@guilherme-svg thank you for your interest in this. The present logo is located at ./static/assets/MyViewLogo.png 

And favicon at ./static/assets/MyViewFavicon.png

The logo is used at the top left of the screen in the navbar on all pages ![IMG-20220124-WA0006.jpg](https://user-images.githubusercontent.com/71138854/157068117-0ef67fec-a23d-4d72-93e3-d47fa4f5828e.jpg)

Favicon is a small emoji on the tab name. 

You can work on whatever you'd like to!

**Comment by guilherme-svg** [comment]
What do you suggest in this proposal?

![rect5646](https://user-images.githubusercontent.com/101021543/157260330-ee7b2459-e426-4a5a-aa1d-821bd6cd96f6.png)

**Comment by guilherme-svg** [comment]
What do you suggest in this proposal?

I tried to follow the first version of the logo.

![rect5646](https://user-images.githubusercontent.com/101021543/157261623-6c64dac4-30cb-4587-b3a5-cf1099b0deda.png)

**Comment by guilherme-svg** [comment]
As soon as I can, I will resize and open

**Comment by prithvijitguha** [comment]
@guilherme-svg  sure, take your time! Thank you so much
