### ISSUE TITLE
Incorrect command to activate environment in windows

### ISSUE THREAD

**Issue by MihirHundiwala** [prithvijitguha/MyView#168]
**Describe the bug**
The readme file misguides about activating the environment in windows
Error encountered : 'myview' is not recognized as an internal or external command, operable program or batch file.

**To Reproduce**
1. Creat a virtual environment
    ```sh
    python -m venv myview
    ```
2. Activate virtual environment

    Linux:
    ```sh
    source myview/bin/activate
    ```

    Windows:
    ```sh
    myview/scripts/activate
    ```

**Expected behavior After running the command**
successful activation of environment

**Solution**
The correct command to activate the environment in windows is to use '\\' instead of '/'

**Comment by prithvijitguha** [comment]
Fixed with #169
